version: '3.8'

services:
  ha_db:
    container_name: ha_db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: epic_db
    ports:
      - "3306:3306"
    restart: always
