server:
  port: 8081
  servlet:
    context-path: /base/v1

spring:
  data:
    mongodb:
      uri: mongodb+srv://herdeiros_aurora:herdeiros_aurora_001@cluster0.otugy2g.mongodb.net/apic_db?retryWrites=true&w=majority&appName=Cluster0

logging:
  level:
    web: DEBUG