server:
  port: 8080
  servlet:
    context-path: /base/v1

#spring:
#  main:
#    banner-mode: console
#  application:
#    name: base services
#  datasource:
#    url: jdbc:mysql://localhost:3306/epic_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
#    username: root
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update
logging:
  level:
    web: DEBUG